header:
  license:
    spdx-id: AGPL-3.0-only
    copyright-owner: Deepchecks
  paths:
    - '**'
  paths-ignore:
    - '**/*.ipynb'
    - '.pylintrc'
    - 'LICENSE'
    - 'deepchecks.egg-info/PKG-INFO'
    - 'makefile'
    - 'notebooks/'
    - 'docs/'
  comment: on-failure

dependency:
  files:
    - requirements.txt
