header:
  license:
    spdx-id: AGPL-3.0-only
    copyright-owner: Deepchecks
    content: |
       ----------------------------------------------------------------------------
       Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)

       This file is part of Deepchecks.
       Deepchecks is distributed under the terms of the GNU Affero General
       Public License (version 3 or later).
       You should have received a copy of the GNU Affero General Public License
       along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
       ----------------------------------------------------------------------------
  paths:
    - '**'
  paths-ignore:
    - '**/*.ipynb'
    - '.pylintrc'
    - 'LICENSE'
    - 'VERSION'
    - 'deepchecks.egg-info/PKG-INFO'
    - 'makefile'
    - 'examples/'
    - 'docs/'
    - 'deepchecks/ppscore.py'
    - '.projectignore'
    - 'MANIFEST.in'
    - '.github/ISSUE_TEMPLATE/'
    - '.github/pull_request_template.md'
    - 'deepchecks/base/resources'
    - 'DESCRIPTION.rst'
  comment: on-failure

dependency:
  files:
    - requirements.txt
