name: Submit Question
description: Ask a general question about deepchecks
title: "QST: "
labels: [question]

body:
  - type: markdown
    attributes:
      value: >
        Since [StackOverflow](https://stackoverflow.com) is better suited towards answering
        usage questions, we ask that all usage questions are first asked on StackOverflow.
  - type: checkboxes
    attributes:
      label: Research
      options:
        - label: >
            I have searched the [[deepchecks] tag](https://stackoverflow.com/questions/tagged/deepchecks)
            on StackOverflow for similar questions.
          required: true
        - label: >
            I have asked my usage related question on [StackOverflow](https://stackoverflow.com).
          required: true
  - type: input
    id: question-link
    attributes:
      label: Link to question on StackOverflow
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: question
    attributes:
      label: Question about deepchecks
      placeholder: |
        ```python
        # Your code here, if applicable

        ```
