# ----------------------------------------------------------------------------
# Copyright (C) 2021 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------
#
{% set data = load_setup_py_data() %}

package:
  name: deepchecks
  version: {{ data.get('version') }}

about:
  home: https://github.com/deepchecks/deepchecks
  license: AGPLv3
  license_file: ../LICENSE
source:
  # Relative path to the parent directory.
  path: ..

build:
  number: 1
  noarch: python

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - pandas
    - numpy
    - scikit-learn>=0.24.2
    - ipython
    - ipykernel
    - ipywidgets
    - tqdm
    - category_encoders
    - scipy
    - typing_extensions
    - dataclasses
    - plotly
    - matplotlib
