package:
  name: deepchecks
  version: "0.0.15_noarch"

about:
  home: https://github.com/deepchecks/deepchecks
  license: AGPLv3
  license_file: ../LICENSE
source:
  # Relative path to the parent directory.
  path: ..

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - pandas
    - numpy
    - scikit-learn
    - ipython
    - ipykernel
    - ipywidgets
    - tqdm
    - category_encoders
    - scipy
    - typing_extensions
    - dataclasses
    - plotly
    - matplotlib
