package:
  name: deepchecks
  version: "0.0.15"

source:
  # Relative path to the parent directory.
  path: ..

build:
  number: 0

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - pandas
    - numpy
    - scikit-learn
    - ipython
    - ipykernel
    - ipywidgets
    - tqdm
    - category_encoders
    - scipy
    - typing_extensions
    - dataclasses
    - plotly
    - matplotlib
