
//shared lib vars
def l = library("jenkins-shared").com.deepchecks.jenkins.SharedLib

def MR_REGEX = '^MR-\\d+$'
def is_branch = false

def agentLabel = "oss-agent"

pipeline{
    agent{
        label agentLabel
    }
    stages{

      stage("Init") {
        steps{
          script {
            log.info ("initialazing Shared Library")
            lib = l.new(this,this,this)

            log.info ("checking if pr or branch")
            is_pr = BRANCH_NAME.matches(MR_REGEX)

          }//script
        }//steps
      }//Calculate Runtime

      stage("Linter") {
        steps{
          script{
            log.info ("checking lint and docstrings")
            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
              sh 'make check'
            }
          }
        }
      }

      stage("Test") {
        steps{
          script {
            log.info ("Testing")
              catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                sh "make tox"
              }
          }//script
        }//steps
      }//tests

    }//stages

    post{
      cleanup{
        cleanWs deleteDirs: true, notFailBuild: true
      }
    }

}//pipeline
