# ----------------------------------------------------------------------------
# Copyright (C) 2021-2023 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------
#
name: Docs Generation

on: [workflow_dispatch]

jobs:
  docs-generation:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Set Up Env
        run: make env
      - name: Regenerate Notebooks
        run: make regenerate-examples
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
      - name: Generating Docs
        run: make docs
      - name: Link Checker
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          set -uxo pipefail

          curl \
            -L --output lychee-v0.8.2-x86_64-unknown-linux-gnu.tar.gz \
            https://github.com/lycheeverse/lychee/releases/download/v0.8.2/lychee-v0.8.2-x86_64-unknown-linux-gnu.tar.gz

          tar -xvzf lychee-v0.8.2-x86_64-unknown-linux-gnu.tar.gz

          ./lychee \
            "./**/*.rst" "./docs/build/html/**/*.html" \
            --base ./docs/build/html \
            --accept=200,403,429 \
            --format markdown \
            --output .lychee.output \
            --exclude-loopback \
            --exclude-mail \
            --no-progress \
            --exclude-file docs/.lycheeignore

          exit_code=$?

          echo
          echo "===== Lychee Output Report ====="
          cat .lychee.output
          echo

          exit ${exit_code}
#      - name: Commit and Push notebooks
#        run: |
#          git add docs/source/examples/*.ipynb
#          git commit -m "Regenerate notebooks"
#          git push origin ${{ github.ref_name }}
