# ----------------------------------------------------------------------------
# Copyright (C) 2021 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------
#
name: Pull Request
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  labels:
    name: Validate Label 
    runs-on: ubuntu-latest

    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "kind/feature, kind/fix, kind/tests, breaking-backwards-compitabillity, chore/ci, chore/documentation"
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: 'help wanted, wontfix, question, good first issue, invalid, duplicate'
