# ----------------------------------------------------------------------------
# Copyright (C) 2021 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------
#
name: Pull Request
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches: [ main ]
jobs:
  labels:
    name: Validate Label
    runs-on: ubuntu-latest

    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "kind/feature, kind/fix, kind/tests, breaking-backwards-compitabillity, chore/ci, chore/documentation"
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: 'help wanted, wontfix, question, good first issue, invalid, duplicate'

  notebooks-update:
    runs-on: ubuntu-latest
    name: Update Example notebooks
    needs: labels
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Update notebooks
        run: ./.github/scripts/update_notebooks.sh
      - name: Set Up Env
        run: make env
      - name: Update version
        uses: test-room-7/action-update-file@v1
        with:
          file-path: docs/source/examples/howto-guides/*.ipynb
          commit-msg: Updating example notebooks
          github-token: ${{ secrets.CI_GH_TOKEN }}

