# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------
#
name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  Security-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --severity-threshold=high
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
  Update-Version:
    runs-on: ubuntu-latest
    needs: Security-Check
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Fetch resources
        run: ./.github/scripts/update_version.sh

      - name: Update version
        uses: test-room-7/action-update-file@v1
        with:
          file-path: VERSION
          commit-msg: New version release
          github-token: ${{ secrets.CI_GH_TOKEN }}
  Create-Release:
    runs-on: ubuntu-latest
    needs: Update-Version
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: "Upload Package"
      run: |
        TAG=$(echo -n "${{ github.event.ref }}" | cut -d '/' -f3)
        make release version=$TAG
      env:
        TWINE_REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
        TWINE_USERNAME: ${{ secrets.REPOSITORY_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          dist/*.whl
          dist/*.tar.gz
          LICENSE
