name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  Create:
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: "Upload Package"
      run: |
        TAG=$(echo -n "${{ github.event.ref }}" | cut -d '/' -f3)
        make release version=$TAG
      env:
        TWINE_REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
        TWINE_USERNAME: ${{ secrets.REPOSITORY_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          dist/*.whl
          dist/*.tar.gz
          LICENSE