# Deepchecks
# Copyright (C) 2021 Deepchecks
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  Create-Release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: "Upload Package"
      run: |
        TAG=$(echo -n "${{ github.event.ref }}" | cut -d '/' -f3)
        make release version=$TAG
      env:
        TWINE_REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
        TWINE_USERNAME: ${{ secrets.REPOSITORY_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          dist/*.whl
          dist/*.tar.gz
          LICENSE

  Update-Docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.GIT_SSH_KEY }}
    - name: Release to GitHub Pages
      env:
        USE_SSH: true
        GIT_USER: git
      run: |
        git config --global user.email "app@deepchecks.com"
        git config --global user.name "deepchecks-ci-bot"
        make website
        cd docs/_website/
        if [ -e package-lock.json ]; then
          npm ci
        else
          npm i
        fi
        npm run deploy